[phases.setup]
nixPkgs = ['nodejs', 'yarn', 'php82', 'php82Packages.composer']

[phases.install]
cmds = [
    'composer require symfony/runtime --no-scripts',
    'composer install --no-dev --no-interaction --prefer-dist --no-scripts',
    'yarn install'
]

[phases.build]
cmds = [
    'yarn build',
    'composer dump-autoload --optimize',
    'APP_RUNTIME_ENV=prod php bin/console cache:clear --env=prod',
    'php bin/console assets:install public'
]

[start]
cmd = 'php-fpm'

[variables]
APP_ENV = "prod"
APP_RUNTIME_ENV = "prod"
